version: "3"
services:
  react-app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node/modules
      - .:/app
  test-app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node/modules
      - .:/app
    command: ["npm", "run", "test"]
